"""Initial migration

Revision ID: 8b08b1d96d72
Revises: 
Create Date: 2025-08-09 11:44:10.780310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b08b1d96d72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_user_configs_id'), table_name='user_configs')
    op.drop_index(op.f('ix_user_configs_key'), table_name='user_configs')
    op.drop_table('user_configs')
    op.add_column('tech_cards', sa.Column('ai_category', sa.JSON(), nullable=True))
    op.add_column('tech_cards', sa.Column('tech_stack', sa.JSON(), nullable=True))
    op.add_column('tech_cards', sa.Column('license', sa.String(length=100), nullable=True))
    op.add_column('tech_cards', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('tech_cards', sa.Column('forks', sa.Integer(), nullable=True))
    op.add_column('tech_cards', sa.Column('issues', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_cards', 'issues')
    op.drop_column('tech_cards', 'forks')
    op.drop_column('tech_cards', 'stars')
    op.drop_column('tech_cards', 'license')
    op.drop_column('tech_cards', 'tech_stack')
    op.drop_column('tech_cards', 'ai_category')
    op.create_table('user_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_configs_key'), 'user_configs', ['key'], unique=1)
    op.create_index(op.f('ix_user_configs_id'), 'user_configs', ['id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('last_sync', sa.DATETIME(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    # ### end Alembic commands ###
